version: '3.8'

services:

jenkins:
  container_name: jenkins
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - CAST_JENKIS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
  ports:
    - 8080:8080
    - 50000:50000
  volumes:
    - ./jenkins_home:/var/jenkins_home
    - ./jcasc:/var/jenkins_home/casc_configs/jenkins.yaml